### ISSUE TITLE
iOS running issue

### ISSUE THREAD

**Issue by beaverbd** [Taracque/cordova-plugin-braintree#10]
Hi. I'm just trying to use this plugin, but on iOS my app instantly closes after i try to start it. What may be wrong? On android everything ok.
For connect this plugin i added this string to my config.xml
 '<'plugin name="cordova-plugin-braintree" spec="https://github.com/Taracque/cordova-plugin-braintree.git"'>' (without single quotes)
I just created blank phonegap app, and added just this one plugin. The same problem

**Comment by beaverbd** [comment]
<plugin name="cordova-plugin-braintree" spec="https://github.com/Taracque/cordova-plugin-braintree.git"/>

**Comment by Taracque** [comment]
Do you see any debug logs? If you are on Mac, you can open platform/ios/PROJECTNAME.xcodeproj with XCode, and you can run it on the app using XCode. There must be some kind of error message when the app crashes.
This happens if one or more braintree libs are not linked to the ios app.
You should see this in your XCode Build Phases:
![kepernyofoto 2017-02-27 - 13 57 11](https://cloud.githubusercontent.com/assets/373777/23362171/c8f3bad6-fcf4-11e6-8ef2-8860edcff3bf.png)

**Comment by beaverbd** [comment]
Termination Description: DYLD, Library not loaded: @rpath/PayPalUtils.framework/PayPalUtils | Referenced from: /var/containers/Bundle/Application/BAFECD46-084C-49C0-9DE9-8D566710D5F7/TestApp.app/TestApp | Reason: image not found
Triggered by Thread:  0

**Comment by Taracque** [comment]
The add_embedded_ios_frameworks.js was not invoked. I don't know PhoneGap, but you can embed the frameworks manually into the xcode project. Open the Build Phases and add the libraries as seen above.

**Comment by beaverbd** [comment]
It would be nice if you could be so kind to  give me any test app on cordova, where this plugin is working and normaly running on ios. Your help is very appreciated!

**Comment by Taracque** [comment]
I've changed the framework embedding hook. Please remove the plugin, and remove the ios platform too:
```bash
cordova plugin rm cordova-plugin-braintree
cordova platform remove ios
cordova plugin add https://github.com/Taracque/cordova-plugin-braintree
cordova platform add ios
```

hope this will work

**Comment by beaverbd** [comment]
Looks like it's a big problem to add plugin that used a custom frameworks into Phonegap. That's what i found
https://issues.apache.org/jira/browse/CB-12290

**Comment by Taracque** [comment]
I've once again reworked the way it embedds the framework. For me it works with the following configuration:
```
Cordova CLI: 6.5.0 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by beaverbd** [comment]
I'm working not in Xcode. And i have no capability to do anything on macOS, means to open Xcode. All i can, build my app with Adobe PhoneGap. There is no functionality to add frameworks into Build Phases

**Comment by Taracque** [comment]
Ok, but what should I do? I've rewritten the code to make a workaround for the bug you mentioned. You should fill a bug report on Adobe's PhoneGap issue tracker, maybe they can help.

**Comment by beaverbd** [comment]
Ok, i tried it on Mac in xCode and it works. Looks like phonegap can't detect custom frameworks inside plugins, and there is no way to define them manualy. And the only way is build app in xCode. 
Ty for help.
