### ISSUE TITLE
Initialize failed

### ISSUE THREAD

**Issue by beaverbd** [Taracque/cordova-plugin-braintree#12]
Hi, i have a new issue. 
I'm calling BraintreePlugin.initialize(token,f1,f2);
And i've got an error callback where the result is "The Braintree client failed to initialize"
Is that a braintree problem or problem inside plugin?

P.S. client token i've got from my server by calling ClientToken.generate();
`$http.get( _apiLinkToGetToken_ )`
`.success(function(result){`
`    BraintreePlugin.initialize(result,`
`    function(){ console.log("Initialized"); },`
`    function(er){ console.log(er); });` <-- HERE
`});`

**Comment by Taracque** [comment]
This error means, that Braintree DropIn failed to initialize for some reason. Most likely your token is wrong. I suggest using a Tokenization key, which can be obtained on your Braintree Sandbox Control Panel. Try with your sandbox tokenization key hardcoded first.

**Comment by beaverbd** [comment]
Ok, it works with Tokenization Key. 
But here is another question.
It shows DropIn, and here what it looks like
![screen shot 2017-03-02 at 18 01 29](https://cloud.githubusercontent.com/assets/13046798/23516109/ebc83212-ff74-11e6-94b9-f6c65e52e67c.png)
Next i click add card and ...
![screen shot 2017-03-02 at 18 01 40](https://cloud.githubusercontent.com/assets/13046798/23516129/009b8a04-ff75-11e6-95cc-9da25a3b9989.png)
Next i put there card info and 
![screen shot 2017-03-02 at 18 01 59](https://cloud.githubusercontent.com/assets/13046798/23516151/101167b0-ff75-11e6-9d79-9ea209f4f74a.png)
click AddCard, and DropIn is closing
Braintree plugin returns me nonce, i am sending nonce to the server, make some magic and money credited in sandbox.

BUT 
Where is data from that options, that i defined for presentDropInPaymentUI? I mean amount and primaryDescription?
And why isn't it asked for CVV code?

**Comment by Taracque** [comment]
The options (amount etc.) are encoded in the nonce. If you need those, store it in your own variable.
CVV can be setup in Braintree Control Panel.

**Comment by beaverbd** [comment]
But if user pays by credit card he doesn't see amount of payment.
Before i show him DropIn, i can tell him that he need to pay 1$, and in DropIn options specify 10$. 
In case Apple pay, there he can see amount of payment.
And next - you say options (amount etc.) encoded in the nonce, but when i'm sending nonce to server and invoking Transaction.Sale(TransactionRequest), in parameter that i have sent. i define a new Amount field, that may differ from amount that takes your presentDropInPaymentUI, and in braintree sandbox it shows amount defined on server, not on client. So how user may be sure that he pays exactly amount defined on client?

**Comment by Taracque** [comment]
Read Braintree docs about Drop-in UI, if that doesn't fit your needs, you have to choose another solution.
https://developers.braintreepayments.com/guides/drop-in/ios/v4
This plugin implements a v5 drop-in on ios (can be found here):
https://github.com/braintree/braintree-ios-drop-in

If you cheat, users will request a refund, what you really don't want. But's that is not a plugin related issue you should ask those one Braintree support.

**Comment by beaverbd** [comment]
So, i'd returned to braintree payments, and i need to initialize braintree client with normal clientToken. I invoked Gateway.ClientToken.generate() and with this token initialization does'nt work.
Is this issue expends only with sandbox clientTokens? Or and in production I need to use TokenizationKey?

**Comment by Taracque** [comment]
Actually I've only tried tokenization key, but according to Braintree docs both should work.
Have you actually checked, that your Client Token is contains a token, and not some error messages?

**Comment by beaverbd** [comment]
It's ok. I've actualy recieve base64 token and it looks fine.

**Comment by Taracque** [comment]
If you decode the base64 token it should looks like this:
```
{"version":2,"authorizationFingerprint":"fc16076dcea64c00bd0a01a91468759a840bfd3aa5d82cafa747a626d6b70e3c|created_at=2017-03-16T18:44:33.989730168+0000\u0026merchant_id=348pk9cgf3bgyw2b\u0026public_key=2n247dv89bq9vmpr","configUrl":"https://api.sandbox.braintreegateway.com:443/merchants/348pk9cgf3bgyw2b/client_api/v1/configuration","challenges":[],"environment":"sandbox","clientApiUrl":"https://api.sandbox.braintreegateway.com:443/merchants/348pk9cgf3bgyw2b/client_api","assetsUrl":"https://assets.braintreegateway.com","authUrl":"https://auth.venmo.sandbox.braintreegateway.com","analytics":{"url":"https://client-analytics.sandbox.braintreegateway.com/348pk9cgf3bgyw2b"},"threeDSecureEnabled":true,"paypalEnabled":true,"paypal":{"displayName":"Acme Widgets, Ltd. (Sandbox)","clientId":null,"privacyUrl":"http://example.com/pp","userAgreementUrl":"http://example.com/tos","baseUrl":"https://assets.braintreegateway.com","assetsUrl":"https://checkout.paypal.com","directBaseUrl":null,"allowHttp":true,"environmentNoNetwork":true,"environment":"offline","unvettedMerchant":false,"braintreeClientId":"masterclient3","billingAgreementsEnabled":true,"merchantAccountId":"acmewidgetsltdsandbox","currencyIsoCode":"USD"},"coinbaseEnabled":false,"merchantId":"348pk9cgf3bgyw2b","venmo":"off"}
```

**Comment by beaverbd** [comment]
{  
   "version":2,
   "authorizationFingerprint":"c1d1ea37d930715adc17e366583f8e514de626b90ac482f7e76442a5ed9cd436|created_at=2017-03-16T18:19:04.344142958+0000\u0026customer_id=ff5476d6-4974-4e2c-9d90-31350ffd4368\u0026merchant_id=bzfm2gqvgnj64spd\u0026public_key=25bjskd7926h8fk4",
   "configUrl":"https://api.sandbox.braintreegateway.com:443/merchants/bzfm2gqvgnj64spd/client_api/v1/configuration",
   "challenges":[  
      "cvv"
   ],
   "environment":"sandbox",
   "clientApiUrl":"https://api.sandbox.braintreegateway.com:443/merchants/bzfm2gqvgnj64spd/client_api",
   "assetsUrl":"https://assets.braintreegateway.com",
   "authUrl":"https://auth.venmo.sandbox.braintreegateway.com",
   "analytics":{  
      "url":"https://client-analytics.sandbox.braintreegateway.com/bzfm2gqvgnj64spd"
   },
   "threeDSecureEnabled":true,
   "paypalEnabled":true,
   "paypal":{  
      "displayName":"NLBe",
      "clientId":null,
      "privacyUrl":"http://example.com/pp",
      "userAgreementUrl":"http://example.com/tos",
      "baseUrl":"https://assets.braintreegateway.com",
      "assetsUrl":"https://checkout.paypal.com",
      "directBaseUrl":null,
      "allowHttp":true,
      "environmentNoNetwork":true,
      "environment":"offline",
      "unvettedMerchant":false,
      "braintreeClientId":"masterclient3",
      "billingAgreementsEnabled":true,
      "merchantAccountId":"nlbe",
      "currencyIsoCode":"USD"
   },
   "coinbaseEnabled":false,
   "merchantId":"bzfm2gqvgnj64spd",
   "venmo":"off",
   "applePay":{  
      "status":"mock",
      "countryCode":"US",
      "currencyCode":"USD",
      "merchantIdentifier":"merchant.com.socialputts.test",
      "supportedNetworks":[  
         "visa",
         "mastercard",
         "amex",
         "discover"
      ]
   }
}

**Comment by Taracque** [comment]
Seems ok. Do you got any error messages? Or it simply doesn't display the Drop-In drawer?

**Comment by beaverbd** [comment]
**2017-03-17 14:20:44.561 MyApp[54050:1780018] [BraintreeSDK] ERROR Invalid client token. Please ensure your server is generating a valid Braintree ClientToken.
2017-03-17 14:20:44.562 MyApp[54050:1780018] [BraintreeSDK] ERROR BTClient could not initialize because the provided clientToken was invalid**
![inked 2017-03-17 14 19 39_li](https://cloud.githubusercontent.com/assets/13046798/24041383/cc8102ce-0b15-11e7-8bd7-468daac4dd9d.jpg)
Error throws in that line

**Comment by Taracque** [comment]
Your token contains the quotes, which shouldn't be there.
If your token starts with \"ey… that it is wrong. Strip quotes from the token before passing it to the plugin.

**Comment by beaverbd** [comment]
I used JSON.parse(token) before transfer it to initialize method, and it works. Looks like js http.get normally awaits a json object.

**Comment by beaverbd** [comment]
And here I again. Now it's android. When i'm calling presentDropInPaymentUI, my app crashes with simple message - Unfortunately, 'appName' has stopped. All i can debug is braintree-plugin.js, error throws after invoking 
`exec(successCallback, failureCallback, PLUGIN_ID, "presentDropInPaymentUI", pluginOptions);`
![2017-03-23 13 17 09](https://cloud.githubusercontent.com/assets/13046798/24243404/b05cd7be-0fc3-11e7-86e2-947241df6896.png)

**Comment by Taracque** [comment]
Disable Android Pay in your Braintree setup fixes this problem.

**Comment by beaverbd** [comment]
Thanks! It's realy helped.
