### ISSUE TITLE
PayPal @ iOS

### ISSUE THREAD

**Issue by ionut-tanasa** [Taracque/cordova-plugin-braintree#14]
Hi there,

Tried your plugin and for Android worked great. Cards and PayPal.

On iOS when I try to use PayPal it throws this error

` PayPal OneTouchCoreSDK: callback URL scheme com.example.app.braintree.payments is not found in .plist`

 `CRITICAL PayPal requires [BTAppSwitch setReturnURLScheme:] to be configured to begin with your app's bundle ID (com.example.app.braintree). Currently, it is set to (com.example.app.braintree.payments).`

Do I have to configure something else?

**Comment by Taracque** [comment]
There must be an URL Type in your XCode project Info session for the "${PRODUCT_BUNDLE_IDENTIFIER}.payments" URL Scheme.
![kepernyofoto 2017-03-17 - 9 43 42](https://cloud.githubusercontent.com/assets/373777/24035548/490f7598-0af6-11e7-9116-6eeb49a7cd17.png)

**Comment by ionut-tanasa** [comment]
@Taracque thank you for the fast reply :) 

Found it in the Braintree's docs -> [Setup for app switch](https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v4#setup-for-app-switch)

Maybe you should add it to the readme? 

Thank you.

**Comment by ionut-tanasa** [comment]
Another quick question, if you don't mind.

How can I add the url type via Cordova's config.xml?

**Comment by Taracque** [comment]
That should be automatically added to your xcode project once you install the plugin. That's a bug, if its not working, and should be fixed.
You cannot add URL Type via config.xml that should be done by a javascript hook.

**Comment by Taracque** [comment]
What is your development environment? My solution only works on macs, as it inserts the needed setup directly into the xcode project.

**Comment by ionut-tanasa** [comment]
It not being added then. I'm on a MBPro. I wouldn't want to remember always to check Xcode. Because I'll forget about it, for sure.

I'd like it to be automated.

I'm trying to do like this, but it doesn't work:

```
<platform name="ios">
    <config-file target="*-Info.plist" parent="CFBundleURLTypes">
      <array>
        <dict>
          <key>CFBundleTypeRole</key>
          <string>Editor</string>
          <key>CFBundleURLSchemes</key>
          <array>
            <string>com.example.app.braintree.payments</string>
          </array>
        </dict>
      </array>
    </config-file>
  </platform>
```

**Comment by Taracque** [comment]
I didn't find a way to add it via plugin.xml or config.xml. That's why I used a JS hook.
At the end of "add_embedded_ios_frameworks.js" there is the code which adds the needed part to xcode info.

**Comment by ionut-tanasa** [comment]
Yeah, just found it. 
https://github.com/Taracque/cordova-plugin-braintree/blob/master/scripts/add_embedded_ios_frameworks.js#L159

But it doesn't update it, nor it throws any error.

The values from https://github.com/Taracque/cordova-plugin-braintree/blob/master/plugin.xml#L61-L67 are getting added though

**Comment by Taracque** [comment]
I've changed the javascript, maybe that will fixes that. Did you added the ios platform after you added the plugin?

**Comment by ionut-tanasa** [comment]
If I do a `	console.log(infoPlist.CFBundleURLTypes)` in your script it logs `undefined`.

I tried both ways. Plugin first then platform. Platform the plugin.

didn't work in both cases

**Comment by ionut-tanasa** [comment]
@Taracque your commit [#d9155f1](https://github.com/Taracque/cordova-plugin-braintree/commit/d9155f1310147d7e9c9662703dbacd43b38d7a2c) fixes it :) 

Would you be kind enough to tag a release, please?

**Comment by Taracque** [comment]
Done
https://github.com/Taracque/cordova-plugin-braintree/releases/tag/v0.5.2

**Comment by ionut-tanasa** [comment]
Thank you :)

Closing.
