### ISSUE TITLE
Is there any call back method to handle invalid card?

### ISSUE THREAD

**Issue by championboylay** [Taracque/cordova-plugin-braintree#15]
When user entered the invalid card number, there is no message stating that the card is invalid. I want to show alert dialog when user enters invalid card number.

**Comment by beaverbd** [comment]
If i right, you gets paymentNonce, and yous must send it to your server. After you invoke Gateway.Transaction.Sale or something else, you will recieve answer that will includes error if card is wrong.

**Comment by Taracque** [comment]
Yes, the card is processed only when you settle the transaction.
You can find further infromation about transaction responses here: https://developers.braintreepayments.com/reference/general/processor-responses/authorization-responses
