### ISSUE TITLE
Crash iOS: dyld: Library not loaded

### ISSUE THREAD

**Issue by lucaele** [Taracque/cordova-plugin-braintree#18]
Hi all,
on iOS 9.3 there is a start error:
dyld: Library not loaded: @rpath/Braintree3DSecure.framework/Braintree3DSecure
  Referenced from: /var/containers/Bundle/Application/BE616B00-B06A-4D88-84BB-FFEB9EE27422/XX.app/XX
  Reason: image not found
(lldb) 

This error appear after
cordova plugin add https://github.com/taracque/cordova-plugin-braintree

Then, on remove this plugin all run correctly.
Any idea?
Luca

**Comment by Taracque** [comment]
Can you please check your XCode project, that you have the Braintree3DSecure.framework in Build Phases and Code Sign On Copy is checked?
![kepernyofoto 2017-04-18 - 11 17 08](https://cloud.githubusercontent.com/assets/373777/25123429/999466fe-2428-11e7-80a4-0beb55447ff0.png)
Probably you didn't removed the ios platform before plugin installation. Try to use the following to install the plugin:
```
    cordova platform remove ios
    cordova plugin add https://github.com/taracque/cordova-plugin-braintree
    cordova platform add ios
```

**Comment by lucaele** [comment]
I followed the instructions. Now I did it again and it seems to work.
I can not explain it now works.
Thanks for your replay
