### ISSUE TITLE
Paypal not opened in app browser

### ISSUE THREAD

**Issue by Almya** [Taracque/cordova-plugin-braintree#20]
Hi,

When I select paypal, it opens the url in the chrome app.

Is there a way to open it in my inappbrowser plugin ?

**Comment by Taracque** [comment]
It is opened in the system browser if user doesn't have  the PayPal app installed. (see https://developers.braintreepayments.com/guides/paypal/overview/android/v2#how-it-works)

**Comment by Almya** [comment]
Great, thanks
