### ISSUE TITLE
Programmatically close menu, Paypal or Credit or **Debit Cart** 

### ISSUE THREAD

**Issue by championboylay** [Taracque/cordova-plugin-braintree#21]
Plugin shows a **menu** to choose  **Paypal** or Credit or **Debit Cart** before going to DropInPaymentUI. I want to close this menu from controller without user action. 
Because I want to redirect from payment page to another page when user is staying payment page without doing action.
 I can redirect to another page but **menu** is still showing in redirected page.
**I tried to use $state.reload() but it is still showing.**
```
function timeoutFunction() {
        $state.reload()
  }
```

![braintree](https://cloud.githubusercontent.com/assets/2637794/25372199/5fb50de8-29ba-11e7-9c8d-ed5ce6ccb859.png)

**Comment by Taracque** [comment]
Sorry, that is not clear for me…
Would you like to change the page behind the Select Payment Method drawer? For that you should use $state.go in ionic.
Or you want to close the drawer after some time automatically?

**Comment by championboylay** [comment]
Yes I want to close the drawer after some time automatically

**Comment by Taracque** [comment]
I think there is no such possibility in Braintree Drop-In.
