### ISSUE TITLE
IOS run issue

### ISSUE THREAD

**Issue by SerhiiZiatko** [Taracque/cordova-plugin-braintree#23]
Hi everyone:) I have a problem with my project when I add this plugin. The application is started and immediately collapses. When I remove this plugin all works fine. I made all according Install guide. In xcode I have this error (please look on screenshots)
http://prntscr.com/f1dkaa,
http://prntscr.com/f1dkv1,
http://prntscr.com/f1dluo,
http://prntscr.com/f1dmee,

My system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

I will be grateful for help:)

**Comment by Taracque** [comment]
Go to General settings, and set Deployment Info / Main Interface to none.
Also be sure Launch Screen File is empty in App Icons and Launchg Images
![kepernyofoto 2017-04-27 - 11 25 05](https://cloud.githubusercontent.com/assets/373777/25477053/7386368e-2b3c-11e7-92ed-09a4857b43e0.png)

**Comment by SerhiiZiatko** [comment]
I'm grateful for the help that helped me. This helped me:) I'm happy now.
