### ISSUE TITLE
How payment works

### ISSUE THREAD

**Issue by rizemesh** [Taracque/cordova-plugin-braintree#26]
Hello,

I configured all the plugin to work with a production envinroment.

I tried to make a payment using a TopUp credit card without any money availability, however the payment went fine... and I received this result

Object
applePayCard: null
card: Object
lastTwo: "XX"
network: "BTCardNetworkVisa"
Object Prototype
localizedDescription: "ending in XX"
nonce: "f9XXXXXX-7d93-XXXa-XXXX-825db0bXXXXX"
payPalAccount: null
threeDSecureCard: null
type: "Visa"
userCancelled: false
venmoAccount: null

Am i not understanding how it works? Have I to call other methods to validate the payment? 

N.B. there is no tracks of the transaction inside the braintree portal.

Thanks
Michele

**Comment by rizemesh** [comment]
Little update,

I tried also with a wrong CCV and it worked...

Another think is that it sounds strange to me it that it does not require the card credit holder details...

Thanks
Michele

**Comment by Taracque** [comment]
Please read Braintree docs. The plugin only prepare the transaction, you have to settle it thru your server. Don't try to figure it out, read the fucking docs instead.
