### ISSUE TITLE
Getting error in ios build after adding this plugin

### ISSUE THREAD

**Issue by engrsandeep** [Taracque/cordova-plugin-braintree#38]
Hi,
Can you please help. Getting below error.
Error: Could not parse project.pbxproj: SyntaxError: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.

**Comment by antkers** [comment]
see https://github.com/Taracque/cordova-plugin-braintree/issues/34

**Comment by engrsandeep** [comment]
Thanks @antkers. It working.

Do it support other languages? I need 4-5 language translations.

Many thanks for help.

**Comment by antkers** [comment]
You're welcome!
Braintree supports 23 languages, see https://developers.braintreepayments.com/guides/drop-in/android/v2 
The drop-in automatically detects the language of the device/app and shows in the UI in that one.
That worked for me on Android but on iOS it always shows up in English, but i haven't investigated that further...

**Comment by engrsandeep** [comment]
Thanks @antkers. Can we look into iOS as it support 23 languages.

Thanks for quick response.

**Comment by engrsandeep** [comment]
@antkers  did you get chance to look on iOS supported languages as its always in english on iOS but show device language in iOS.

**Comment by antkers** [comment]
Hello @engrsandeep, sorr but I didn't have time to look into that by now. For the moment it is okay for me that it is only in English on ios, but it will be a topic for me in the next couple of months...

**Comment by engrsandeep** [comment]
Just one thing, i did not find version of iOS sdk used? is it latest one? if yes then i can open issue in braintree drop-in.
