### ISSUE TITLE
Working as intended?

### ISSUE THREAD

**Issue by SpellCraft** [Taracque/cordova-plugin-braintree#8]
Hello!

I've been looking into switching over to Braintree, mainly due to Paypal not accepting DCC payments for my country (Norway).

I went through and followed your Readme, setting up the Braintree client and creating my testing payment.
I'm using the tokenization key you generate from "My account" over at Braintree.

The sandbox key works fine so I decided that since I didn't encounter any errors, I'd try the live version right out of the box.  I signed up on Briantree for a business account and generated a new **_live_** tokenization key, testing first on a credit card I know has no funds on it or insufficient funds to check my error reporting.

Payments are going through regardless if I have funds or not and it doesn't seem like I'm being charged anything from my account either.  Is this working as intended?

**Log output:**
```
payment success: {
    "threeDSecureCard": {
        "liabilityShifted": false,
        "liabilityShiftPossible": false
    },
    "type": "Visa",
    "localizedDescription": "ending in **",
    "card": {
        "network": "Visa",
        "lastTwo": "**"
    },
    "nonce": "********-****-****-****-************"
}
```

This is with a credit card that doesn't have any funds available what-so-ever.

What I'm seeing though is after you've scanned/typed in your card number and selected the expiration date, then proceed to click "Add Card", the drop in menu just closes and you're given the success result without even being asked for your CCV2 code.

Is this working as intended?  Is there something I'm missing or doing wrong?

I'm trying this out on Android for the record. Cordova@Android platform v6.1.2

**Comment by SpellCraft** [comment]
My code for reference:
```javascript
BraintreePlugin.initialize(token, function () {
    console.log('Braintree Initialized!');
}, function (error) {
    console.log('Something went wrong: ' + JSON.stringify(error, null, 4));
});


// Setup a test payment
var options = {
    amount: "1.00",
    primaryDescription: "Testing"
};

BraintreePlugin.presentDropInPaymentUI(options, function (result) {
    if (result.userCancelled) {
        console.log('Purchase cancelled!');
    } else {
        console.log('Payment accepted!');
        console.log('Payment Nonce: ' + result.nonce);
        console.log("payment success: " + JSON.stringify(result, null, 4));
    }
}, function (error) {
    console.log('Something went wrong: ' + JSON.stringify(error, null, 4));
});
```

**Comment by Taracque** [comment]
I suggest you to put the presendDropInPaymentUI to the onSuccess part of the initialize call.
Once you have the payment nonce, it must be sent to braintree server by your server ( https://developers.braintreepayments.com/start/hello-server/php ) to create the transaction.
Basically on the client side you create a transaction which is approved by the user and you have to settle the transaction via your server.

**Comment by SpellCraft** [comment]
Ah right, I didn't know about this at all. Thanks for clarifying that for me!
Maybe the readme should be amended to include this, for example?

Thanks again!
