### ISSUE TITLE
Help me create a new Braintree Plugin

### ISSUE THREAD

**Issue by EinfachHans** [Taracque/cordova-plugin-braintree#82]
Hey everybody,

because the official Braintree plugin is not maintained and don't uses latest Mobile SDK's, i decided to create my own plugin 👨🏼‍💻

➡ https://github.com/HansKrywaa/cordova-plugin-braintree-sdk 🎉

To make it work like it should, it would be great if some of you can help me develop it by testing it. If you already have experience with Braintree (and maybe using it already somehow) this would be great.

As it is not released yet, you need to install it directly via git:
```
cordova plugin add https://github.com/HansKrywaa/cordova-plugin-braintree-sdk.git
```

Please make sure to read the **README.md** in the Project to correctly setup everything. If you found bugs, or missing stuff, feel free to open an issue.

Thanks to everybody supporting me with this project! ❤️

**Comment by faraz9x** [comment]
Hi, Glad tohear that, it will be a great help for many.
We just switched to using a webview for payments instead of the plugin. But would like to have a plugin for next projects.
Would try to test it soon
