### ISSUE TITLE
Is 3D Secure support?

### ISSUE THREAD

**Issue by championboylay** [Taracque/cordova-plugin-braintree#9]
I would like to know, does **cordova-plugin-braintree**, plugin support 3D secure? I found 3dsecure branch and how can it test it?

**Comment by Taracque** [comment]
Register a Braintree Sandbox account and you can use it for test.
https://www.braintreepayments.com/sandbox

**Comment by championboylay** [comment]
Is there a way to check a card is enrolled in a 3D Secure program? At javascript, I can check a card is enrolled or not by using following code.
`client.verify3DS({
  amount: 500,creditCard: NONCE_FROM_DROPIN_OR_CUSTOM_INTEGRATION
}, .........`

When a card is enrolled in a 3D Secure, customer will be prompted to authenticate using their bank login credentials. It does not prompted when I am using plugin.

**Comment by championboylay** [comment]
I found it on 3dsecure branch. I have check out 3dsecure branch and it is worked as expected.

`    BraintreePlugin.presentThreeDSecureVerification(secureoptions, function(result){.....                                    })`
